### ISSUE TITLE
translatable element names in item-chat 

### ISSUE THREAD

**Issue by marlon-omc** [yakovliam-com/spacechat#16]
#I would like **item-chat** to be able to translate the name of the item when using [item], for example:

using [item] in a diamond pickaxe comes out **[diamond pickaxe]** and with "translatable element" the article can  be translated into Spanish and get [pico de diamante]

**Comment by yakovliam** [comment]
Are you saying that you want to use a translations API to translate the text? Because item display names that have been modified aren't compatible with the namespaced key translations system that clients use. It's embedded in the client, not the server so players who aren't using the Spanish locale would see it in Spanish despite using English.

**Comment by yakovliam** [comment]
This has been done! Thanks for the suggestion.
